### PR TITLE
feat: update to ink@3

### LINKED ISSUE #60: Migrate to Ink V3
Just a placeholder issue for my PR to update to V3

### PR DESCRIPTION
**Pull request by dylanarmstrong**
Fixes #60 

## Description
Updates support to ink v3, as well as fixes some complaints that xo had about linting.

## Testing
Tests continue to pass, updated to latest ava and xo as well.
Examples can be run with:
```
npm run build
./node_modules/.bin/babel examples/basic.js -o examples/basic.lib.js && node examples/basic.lib.js
./node_modules/.bin/babel examples/custom.js -o examples/custom.lib.js && node examples/custom.lib.js
```

### CODE REVIEW

**Comment by maticzav** [comment]
Nice! Thank you for opening up the pull request. I’ll merge it right away.😄

**Comment by H3RSKO** [comment]
Hey @dylanarmstrong, feel like making ink-tab compatible with V3? Pretty please?

https://github.com/jdeniau/ink-tab

**Comment by dylanarmstrong** [comment]
@h3rsko I was looking at this, and it looks like the author just released a 4.0.0 version with v3 support for you :)

**Comment by H3RSKO** [comment]
Yup! :-)

**Comment by loilo** [comment]
Hey there. 👋  Anything I could help here to get the v3-compatible `ink-table` to npm? :)

**Comment by maticzav** [comment]
Has the release failed?

**Comment by loilo** [comment]
Well, the last release on npm is from 1 year ago. 🤷‍♂️

**Pull request merged**
