### PR TITLE
v2 Migration

### PR DESCRIPTION
**Pull request by hedgerh**
Did this a couple of weeks ago.  Got it work but I don't understand the code well enough to know if I fixed it in a good way or not.  Don't have time to test it out, but just wanted to open the MR to get it out there.

### CODE REVIEW

**Comment by maticzav** [comment]
Hey 👋,

Thanks a lot for putting this together. Are you sure that's all there needs to be changed? I haven't touched the code for quite a while but there seems to be a lot of it.

**Comment by LitoMore** [comment]
@maticzav Let me help you to review this PR.

**Comment by LitoMore** [comment]
@hedgerh I see all file mode has been changed to `755`. We should not change the file mode in this project.

```
-rwxr-xr-x    1 jiong.huang  jiong.huang   1.9K Apr 25 14:15 README.md
drwxr-xr-x    3 jiong.huang  jiong.huang    96B Apr 25 14:13 dist
drwxr-xr-x    4 jiong.huang  jiong.huang   128B Apr 25 14:15 examples
drwxr-xr-x    3 jiong.huang  jiong.huang    96B Apr 25 14:15 media
drwxr-xr-x  706 jiong.huang  jiong.huang    22K Apr 25 14:13 node_modules
-rwxr-xr-x    1 jiong.huang  jiong.huang   493K Apr 25 14:15 package-lock.json
-rwxr-xr-x    1 jiong.huang  jiong.huang   1.6K Apr 25 14:15 package.json
-rwxr-xr-x    1 jiong.huang  jiong.huang   112B Apr 25 14:15 renovate.json
drwxr-xr-x    3 jiong.huang  jiong.huang    96B Apr 25 14:15 src
-rwxr-xr-x    1 jiong.huang  jiong.huang   7.0K Apr 25 14:15 test.js
-rwxr-xr-x    1 jiong.huang  jiong.huang   279K Apr 25 14:15 yarn.lock
```

**Comment by hedgerh** [comment]
@LitoMore any interest in picking up work on this PR? I mostly got it here by fooling around.  I can keep working on it, but don’t have a great understanding of the code.  All good if you’re not able to.

**Comment by LitoMore** [comment]
@hedgerh Sure. Let me continue with your PR. Actually I already have a branch for this migration work.

**Comment by hedgerh** [comment]
Really appreciate it! Hope my work was helpful.  Let me know if you need anything

**Comment by LitoMore** [comment]
My v2 migration pull request is here: https://github.com/maticzav/ink-table/pull/31.

**Pull request closed without merging**
